# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_llmjson_wrappers", use_symbols = TRUE, package_name = "llmjson")

#' @usage NULL
#' @useDynLib llmjson, .registration = TRUE
NULL

#' Repair malformed JSON strings
#'
#' This function repairs malformed JSON strings, particularly those generated
#' by Large Language Models. It handles missing quotes, trailing commas,
#' unquoted keys, and other common JSON syntax errors.
#'
#' @param json_str A character string containing malformed JSON
#' @param schema Optional schema definition for validation and type conversion
#' @param return_objects Logical indicating whether to return R objects (TRUE) or JSON string (FALSE, default)
#' @param ensure_ascii Logical; if TRUE, escape non-ASCII characters
#' @param int64 Policy for handling 64-bit integers: "double" (default, may lose precision), "string" (preserves exact value), or "bit64" (requires bit64 package)
#' @return A character string containing the repaired JSON, or an R object if return_objects is TRUE
#' @export
#' @examples
#' repair_json_str('{"key": "value",}')  # Removes trailing comma
#' repair_json_str('{key: "value"}')     # Adds quotes around unquoted key
#' repair_json_str('{"key": "value"}', return_objects = TRUE)  # Returns R list
#'
#' # Handle large integers (beyond i32 range)
#' json_str <- '{"id": 9007199254740993}'
#' repair_json_str(json_str, return_objects = TRUE, int64 = "string")  # Preserves as "9007199254740993"
#' repair_json_str(json_str, return_objects = TRUE, int64 = "double")  # May lose precision
#' repair_json_str(json_str, return_objects = TRUE, int64 = "bit64")   # Requires bit64 package
repair_json_str <- function(json_str, schema = NULL, return_objects = FALSE, ensure_ascii = TRUE, int64 = "double") .Call(wrap__repair_json_str, json_str, schema, return_objects, ensure_ascii, int64)

#' Repair malformed JSON from a file
#'
#' This function reads a file containing malformed JSON and repairs it.
#'
#' @param path A character string with the file path
#' @param schema Optional schema definition for validation and type conversion
#' @param return_objects Logical indicating whether to return R objects (TRUE) or JSON string (FALSE, default)
#' @param ensure_ascii Logical; if TRUE, escape non-ASCII characters
#' @param int64 Policy for handling 64-bit integers: "double" (default, may lose precision), "string" (preserves exact value), or "bit64" (requires bit64 package)
#' @return A character string containing the repaired JSON, or an R object if return_objects is TRUE
#' @export
#' @examples
#' \dontrun{
#' repair_json_file("malformed.json")
#' repair_json_file("malformed.json", return_objects = TRUE)
#' repair_json_file("data.json", return_objects = TRUE, int64 = "string")  # Preserve large integers
#' }
repair_json_file <- function(path, schema = NULL, return_objects = FALSE, ensure_ascii = TRUE, int64 = "double") .Call(wrap__repair_json_file, path, schema, return_objects, ensure_ascii, int64)

#' Repair malformed JSON from raw bytes
#'
#' This function repairs malformed JSON from a raw vector of bytes.
#'
#' @param raw_bytes A raw vector containing malformed JSON bytes
#' @param schema Optional schema definition for validation and type conversion
#' @param return_objects Logical indicating whether to return R objects (TRUE) or JSON string (FALSE, default)
#' @param ensure_ascii Logical; if TRUE, escape non-ASCII characters
#' @param int64 Policy for handling 64-bit integers: "double" (default, may lose precision), "string" (preserves exact value), or "bit64" (requires bit64 package)
#' @return A character string containing the repaired JSON, or an R object if return_objects is TRUE
#' @export
#' @examples
#' \dontrun{
#' raw_data <- charToRaw('{"key": "value",}')
#' repair_json_raw(raw_data)
#' repair_json_raw(raw_data, return_objects = TRUE)
#' repair_json_raw(raw_data, return_objects = TRUE, int64 = "bit64")  # Use bit64 for large integers
#' }
repair_json_raw <- function(raw_bytes, schema = NULL, return_objects = FALSE, ensure_ascii = TRUE, int64 = "double") .Call(wrap__repair_json_raw, raw_bytes, schema, return_objects, ensure_ascii, int64)

LLMJsonSchemaBuilt <- new.env(parent = emptyenv())

LLMJsonSchemaBuilt$new <- function(robj) .Call(wrap__LLMJsonSchemaBuilt__new, robj)

LLMJsonSchemaBuilt$format <- function() .Call(wrap__LLMJsonSchemaBuilt__format, self)

#' @export
`$.LLMJsonSchemaBuilt` <- function (self, name) { func <- LLMJsonSchemaBuilt[[name]]; environment(func) <- environment(); func }

#' @export
`[[.LLMJsonSchemaBuilt` <- `$.LLMJsonSchemaBuilt`


# nolint end
