# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_llmjson_wrappers", use_symbols = TRUE, package_name = "llmjson")

#' @usage NULL
#' @useDynLib llmjson, .registration = TRUE
NULL

#' Repair malformed JSON strings
#'
#' This function repairs malformed JSON strings, particularly those generated
#' by Large Language Models. It handles missing quotes, trailing commas,
#' unquoted keys, and other common JSON syntax errors.
#'
#' @param json_str A character string containing malformed JSON
#' @return A character string containing the repaired JSON
#' @export
#' @examples
#' repair_json_str('{"key": "value",}')  # Removes trailing comma
#' repair_json_str('{key: "value"}')     # Adds quotes around unquoted key
repair_json_str <- function(json_str) .Call(wrap__repair_json_str, json_str)

#' Repair malformed JSON from a file
#'
#' This function reads a file containing malformed JSON and repairs it.
#'
#' @param path A character string with the file path
#' @return A character string containing the repaired JSON, or an empty object on error
#' @export
#' @examples
#' \dontrun{
#' repair_json_file("malformed.json")
#' }
repair_json_file <- function(path) .Call(wrap__repair_json_file, path)

#' Repair malformed JSON from raw bytes
#'
#' This function repairs malformed JSON from a raw vector of bytes.
#'
#' @param raw_bytes A raw vector containing malformed JSON bytes
#' @return A character string containing the repaired JSON, or an empty object on error
#' @export
#' @examples
#' \dontrun{
#' raw_data <- charToRaw('{"key": "value",}')
#' repair_json_raw(raw_data)
#' }
repair_json_raw <- function(raw_bytes) .Call(wrap__repair_json_raw, raw_bytes)


# nolint end
